In [45]:
import numpy as np

# Numpy Arrays

## Formas de crear arrays de numpy.

In [46]:
# Bien, hablemos sobre las diferentes formas de crear arrays de numpy.
# Una forma de crear un array de numpy es a partir de un objeto existente, como una lista.
# En Python, tienes listas integradas que usan corchetes, así que puedo decir mi_lista y ponerle uno, dos, tres.
mylist = [1,2,3]

In [47]:
# Si reviso el tipo de este objeto, mylist, es de tipo lista.
type (mylist)

list

In [48]:
# Si quiero transformar esta lista en un array, puedo decir np.array y luego pasarle ese objeto mi_lista y lo transformará en un array.
np.array(mylist)

array([1, 2, 3])

In [49]:
# Ten en cuenta que esto no afecta permanentemente la lista.
# Si digo type(mi_lista), sigue siendo una lista.
type(mylist)

list

In [50]:
# Si realmente quiero el array, necesito decir algo como array = np.array(mi_lista).
# Entonces tengo este objeto (o variable) array, que es un array de numpy.
arr = np.array(mylist)
arr

array([1, 2, 3])

## Matriz

In [51]:
# Algo más útil que transformar una lista de Python a un array de numpy, es transformar una lista anidada en un array de numpy.
# Esto se llama MATRIZ.
mylist = [[1,2,3],[4,5,6],[7,8,9]]
mylist

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [52]:
# Ahora Jupyter realmente lo muestra como una matriz bidimensional.
# Puedes verificar cuántas dimensiones tiene basado en la cantidad de corchetes que aparecen al principio o al final.
# Esto es bidimensional porque tenemos un eje x y un eje y, esencialmente una matriz de dos dimensiones.
np.array(mylist)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
mymatrix = np.array(mylist)

In [54]:
# Existen métodos integrados y propiedades para este array.
# Si lo llamo mymatrix y lo ejecuto para definirlo, luego puedo decir mymatrix. y presionar tabulador. Notarás que hay un montón de métodos y atributos diferentes que puedo usar en este array de numpy.
# Uno de los más útiles es shape y devolverá la forma real del array, que es 3 por 3.
mymatrix.shape

(3, 3)

In [55]:
# Esa es una manera de convertir una lista de Python existente en un array de numpy.
# Sin embargo, hay muchos métodos integrados realmente útiles para arrays muy comunes.

In [56]:
# Primero, hablemos de los métodos integrados.
# Uno de los más útiles es np.arange y la forma en que funciona arange, puedes hacer shift+tab y te dará la información.
# Es muy parecido al range incorporado de Python, donde tienes un inicio, un fin y un tamaño de paso.
# Podemos empezar en el índice 0 y llegar hasta 10 (pero sin incluirlo!), el índice final.
# Fíjate que empieza en 0 y llega hasta, pero sin incluir, el 10.
# El inicio es inclusivo, el final es exclusivo, y tenemos de 0 hasta 9.
mynewmatrix = np.array(mylist)
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
# Luego podemos añadir el parámetro de tamaño de paso. Por defecto, el tamaño de paso es uno, sube de 1 en 1.
# Pero si ponemos 2 como parámetro de step, entonces sube de dos en dos, pero sin incluir el número final.
np.arange(0,10,2)

# Si quisiera ver el diez, simplemente pondría como final el once, y así veo el diez.

array([0, 2, 4, 6, 8])

In [58]:
# También podemos tener ceros y unos.
# Puedo decir np.zeros y si pongo un solo número, como cinco, me devuelve un array de cinco ceros.
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [59]:
# Fíjate que después del cero aparece un punto, indicando que es un número flotante.
# Si revisamos 0.0, el tipo de esto es float, no es un entero.
# Es lo mismo si simplemente dices cero punto, también es un float. Así que eso es lo que significa, que son números de punto flotante.
type(0.)

float

In [60]:
# Pero también puedes pasar una tupla.
# Fíjate en otro par de paréntesis aquí con una forma distinta.
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [61]:
# Lo mismo con np.ones. Como ya habrás adivinado, es esencialmente la misma operación pero ahora puedes pedir unos.
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [62]:
# Lo interesante de esto es que numpy te permite hacer operaciones que se aplican a todos los números del array (broadcasted).
# Es decir, si tomo un array de unos y le sumo 4, numpy automáticamente va a sumar el número 4 a cada uno de los elementos.
# Esto no se puede hacer con una lista normal de Python, por eso la gente usa numpy en primer lugar.
# Así que, por ejemplo, si tenemos unos de numpy y le sumamos cuatro, nos da cuatro unos.
np.ones((5,5))+4

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [63]:
# Puedo incluso multiplicar esto por 100 y entonces tengo cuatro "cien".
np.ones(4)*100

array([100., 100., 100., 100.])

In [64]:
# Si intento hacer lo mismo con una lista normal de Python, aquí tengo cuatro unos.
# Es una lista (no un array), si intento multiplicarla por 100, lo que obtengo es la lista repetida 100 veces. No hace la operación.
[1,1,1,1]*100

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,


In [65]:
# Y si intento sumar diez (+ 10), obtendré un error.
# Me dirá que no puede concatenar una lista con un entero porque son tipos de datos diferentes.
# Numpy no tiene este problema.
[1,1,1,1]+10

TypeError: can only concatenate list (not "int") to list

## Sigamos con un par de formas más de crear arrays de numpy: Tenemos la posibilidad de crear arrays espaciados linealmente, que devuelven números equidistantes en un intervalo especificado.

In [66]:
# Lo que hacemos es decir np.linspace, luego pones un inicio, un final, y luego cuántos elementos queremos entre el inicio y el final que sean equidistantes.
# Por ejemplo, si pido tres números entre 0 y 10, me da 0, 5 y 10.
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [67]:
# Puedo pedir más, por ejemplo 20 números equidistantes entre 0 y 10, y me devuelve esos 20 números empezando en 0 y llegando hasta 10 inclusive.
# Representa números equidistantes en un intervalo especificado, con un inicio, un final y la cantidad de números que quieras.
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

## Crear rápidamente una matriz identidad

In [68]:
# Hay una forma de crear rápidamente una matriz identidad, y eso es con np.eye.
# Aquí le pones un solo número y te devuelve una matriz identidad de ese tamaño (por ejemplo, 5 por 5).
# Una matriz identidad es una matriz que tiene unos en la diagonal principal y todo lo demás es cero.
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Formas de crear números aleatorios con numpy.

### Distribución uniforme: np.random.rand

In [69]:
# Hay muchas formas de crear números aleatorios con numpy. Una forma de hacerlo es llamando a np.random.
# Y si aquí presionas Tab, notarás que hay muchos métodos diferentes para crear números aleatorios.
np.random.

SyntaxError: invalid syntax (192756570.py, line 3)

In [70]:
# El primero que vamos a ver es rand, que básicamente genera una muestra aleatoria de una distribución uniforme entre 0 y 1.
# Esto significa que si pones un solo número aquí, por ejemplo uno, te devuelve un número aleatorio entre 0 y 1, y es una distribución uniforme, lo que significa que todos los números entre 0 y 1 tienen la misma probabilidad de ser elegidos.
np.random.rand(1)
# Si escribes 4 aquí, te devolverá 4 números aleatorios. Así puedes ver los 4 números aleatorios. También puedes pasarle una forma. Por ejemplo, puedes poner cinco coma cinco, y te devolverá un array de 5x5 de números aleatorios entre 0 y 1.
np.random.rand(4)
np.random.rand(5,5)

array([[0.46348377, 0.0306814 , 0.09032208, 0.88030571, 0.67272966],
       [0.80320886, 0.89498623, 0.94090241, 0.151571  , 0.14769946],
       [0.98517554, 0.7187688 , 0.6870754 , 0.47708197, 0.42854215],
       [0.32033115, 0.22239564, 0.53089932, 0.91350251, 0.09201217],
       [0.83284133, 0.8163503 , 0.6338194 , 0.42902361, 0.71871624]])

### Distribución normal:np.random.randn - np.random.normal

In [71]:
# Eso es con una distribución uniforme.
# También existe la posibilidad de hacer lo mismo con una distribución normal. Es decir, podemos decir np.random.randn y esto devuelve una muestra (o varias, dependiendo de lo que le pidas) de la distribución normal estándar.
# La distribución normal estándar tiene una media de 0 y una desviación estándar de 1.
# Así que podemos pedir un número de esta distribución normal estándar, y puedes ver que es un valor alrededor de 0, quizás negativo o positivo.
np.random.randn(1)

# Podemos pedir 10 números aleatorios, que estarán distribuidos normalmente alrededor de 0 y tendrán una desviación estándar de 1.
np.random.randn(10)

array([-0.95949693, -2.0458215 , -0.11294747,  0.60949337, -1.25398981,
       -1.29323097,  1.88779014, -0.71545436, -0.03733028,  1.21397127])

In [72]:
# Si quieres especificar tu propia media y desviación estándar (“sigma”), puedes usar random.normal y, si haces shift+tab, puedes ingresar el parámetro de “loc” (que es la media) y “scale” (que es la desviación estándar).
# np.random.normal()

### Número aleatorio dentro un intervalo: np.random.randint

In [73]:
# Otro método muy útil es randint, así que podemos decir np.random.randint, y esto lo que hace es devolver enteros aleatorios desde un valor bajo (inclusive) hasta un valor alto (exclusivo). Así que puedes decidir los límites, por ejemplo: del 1 al 100 y te devuelve un número aleatorio entre 1 y 100.
#Si sigues ejecutando la celda, obtendrás diferentes números aleatorios.
np.random.randint(1,100)

# Puedes pedir una cantidad determinada de números entre 1 y 100, por ejemplo 10, y te devuelve esos 10 números aleatorios en ese rango.
np.random.randint(1,100,10)

array([94, 75, 58, 87, 94,  3, 36,  8, 96, 77])

## Seed

In [74]:
# Probablemente habrás notado que estás obteniendo resultados aleatorios distintos a los míos. Lo que puedes hacer es establecer una “semilla” (seed), que define el estado aleatorio inicial. Así los resultados se pueden reproducir.
# Esto se hace escribiendo en una celda: np.random.seed() y adentro pones cualquier número para inicializar el generador de números aleatorios. Mientras uses el mismo número que yo, obtendrás los mismos números aleatorios.
# Por ejemplo, puedes poner 42, o 101, o cualquier número; realmente da igual mientras seas consistente y estés comparando con la generación histórica de números.
np.random.seed(42)
np.random.rand(4)


# Mientras ambos estén en la misma celda y la ejecutes, deberías ver exactamente los mismos cuatro números aleatorios que yo.
# El número 42 no tiene ningún significado especial aquí, es solo un número cualquiera que hemos elegido. Mientras tú uses el mismo número, obtendrás los mismos resultados.
# Para que quede más claro, cambia la semilla a 101, vuelve a ejecutar, y verás cuatro números diferentes (pero siempre los mismos cada vez que uses esa semilla). O puedes pedir un array 5x5 y verás siempre los mismos cuando uses el mismo seed.
# Es importante que sepas que estos resultados coinciden porque la semilla y el generador aleatorio están en la misma celda. Si los llamas en celdas diferentes, el resultado será diferente. Así que, si quieres asegurarte de obtener los mismos números que yo, mantén la seed y la llamada al método de números aleatorios en la misma celda, como hago en los videos.

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

## Atributos y métodos de los arrays.

In [75]:
# Rápidamente voy a crear un array
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [76]:
# Después, voy a crear otro:
ranarr = np.random.randint(0, 50, 10) #me da diez números aleatorios entre 0 y 50.
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

### Reshape: puedes transformar un vector unidimensional en otra cosa.

In [77]:
# Como mencioné antes, si tienes un array, puedes ver su forma con .shape, pero a veces no quieres todo como un vector unidimensional, sino que deseas un array bidimensional.
arr.shape

(25,)

In [78]:
# Para hacer esto, llamas al método reshape y le pasas la nueva forma, por ejemplo 5x5. Eso te devolverá un array de 5 filas y 5 columnas.
arr.reshape(5,5) 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [79]:
# Algo importante: no puedes elegir cualquier valor al azar. Por ejemplo, si pides un array 5x3, recibirás un error, porque no puedes acomodar 25 elementos en una forma de 5x3 (eso solo serían 15 elementos).
# Así que, si ves el error de “cannot reshape array”, revisa cuántos elementos tienes y la forma a la que quieres cambiarlo.
arr.reshape(5,3) 

ValueError: cannot reshape array of size 25 into shape (5,3)

### Argmax y Argmin

In [80]:
# Supongamos que tenemos nuestro random array, unos números aleatorios.
# Si queremos saber cuál es el número máximo, podemos usar .max(), y te devuelve el valor máximo. Lo mismo para el mínimo con .min().
ranarr.max()

np.int64(39)

In [81]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [82]:
# Si quieres saber la posición (el índice) donde están esos valores máximo y mínimo, puedes usar .argmax() y .argmin(). Esto te devuelve el índice donde se encuentra ese valor dentro del array.
ranarr.argmax()

np.int64(7)

# Numpy Indexing and Selection

- La indexación nos va a permitir obtener un solo elemento de un array de una o dos dimensiones.
- La selección nos permitirá obtener una porción (slice) o un conjunto de elementos de un array unidimensional o bidimensional.

In [83]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Indexación y selección con corchetes

In [84]:
# Supongamos que quiero obtener un solo valor de ese array unidimensional. Simplemente se usan corchetes y se pasa el índice del valor que buscas.
# Por ejemplo, en la posición índice 8 está el número 8. Así que debería ver un 8.
arr[8]

np.int64(8)

In [85]:
# Si quieres obtener valores dentro de un rango, igual que con listas de Python, solo pones en los corchetes el índice inicial, dos puntos, y el índice final (sin incluirlo). Por ejemplo, del 1 al 5: ponemos [1:5], y obtenemos 1, 2, 3, 4.
arr[1:5]

array([1, 2, 3, 4])

In [86]:
#Si quisiera incluir también el 0, podría hacer [0:5], o simplemente [ :5], lo que significa ir desde el principio hasta el índice 5 (sin incluirlo).
arr[:5]

array([0, 1, 2, 3, 4])

In [87]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [88]:
# Ahora, como mencioné antes, también podemos aplicar broadcasting; es decir, los arrays de numpy permiten aplicar funciones y operaciones a todos los elementos a la vez, lo que no ocurre con las listas de Python.
# Por ejemplo, puedo tomar mi array y sumarle un número a cada elemento, o dividir todos los números.
# Observa que los cambios no son permanentes. Tendrías que guardar el resultado en una nueva variable o sobrescribir la variable original para que los cambios sean permanentes.
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [89]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
# Algo importante sobre los slices es que cuando tomas un fragmento (slice) de un array, ese fragmento sigue apuntando al array original, no es una copia independiente.
# Aquí está nuestro array original del 0 al 10.
# Si tomamos un slice con array[0:6] y lo guardamos en una variable, ese slice muestra los valores de 0 a 5.
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [91]:
slice_of_arr[:]

array([0, 1, 2, 3, 4, 5])

In [92]:
# Si luego le asignas un valor a todo el slice (por ej lo igualas a 99), todos esos valores en la porción seleccionada van a cambiar a 99,
# y también cambiarán en el array original.
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [93]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [94]:
#Esto ocurre porque el slice sigue apuntando al array original.
# Así que, si no quieres que tu array original se modifique, debes crear una copia explícita, usando el método .copy().
# Así tendrás una copia independiente en memoria, y los cambios en la copia no afectarán al original.
arr_copy = arr.copy()
arr_copy[:] = 1000
arr_copy

array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [95]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexación y selección en arrays bidimensionales (matrices)

In [96]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [97]:
arr_2d.shape

(3, 3)

In [98]:
# Para extraer elementos o filas/columnas de un array bidimensional, primero se indica el índice de la fila, y después el de la columna.
# Por ejemplo, para obtener solo una fila (por ejemplo, la fila en índice 1, que contiene 20, 25, 30):
arr_2d[1]

array([20, 25, 30])

In [99]:
# Si queremos sólo el 25 (fila 1, columna 1)
arr_2d[1,1]

np.int64(25)

In [100]:
# Para seleccionar más de un número
arr_2d[:2] #todo menos la fila 2

array([[ 5, 10, 15],
       [20, 25, 30]])

In [ ]:
arr_2d[:2,1:] #todo menos la fila 2; y luego desde la columna 1 hasta el final

array([[10, 15],
       [25, 30]])

## Selección condicional

La selección condicional te permite usar operadores de comparación para filtrar elementos de un array.

In [102]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [103]:
# Si tienes un array con los números del 1 al 10, puedes preguntar cuáles son mayores que 4.
# Esto devuelve un array de valores booleanos (True / False), uno por cada elemento.
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [105]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
# Luego puedo realizar una selección condicional al pasar esta matriz booleana como filtro a mi matriz original.
# Observe que solo volverá a donde las ubicaciones del índice eran verdaderas.
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [107]:
# Otra forma de decir eso:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [109]:
arr[arr == 2]

array([2])

# Numpy Operations

In [111]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
# Quiero reiterar que cuando realizas operaciones en numpy, a menudo se hacen elemento por elemento,
# es decir, la operación se transmite (broadcasted) a lo largo de todo el array.

In [112]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [113]:
arr/100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09])

In [114]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [115]:
(arr+2)/100

array([0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11])

In [117]:
# Puedes ver que podemos hacer operaciones aritméticas elemento a elemento en todo el array.
# También podemos realizar operaciones similares con dos arrays de la misma forma.
# Por ejemplo, puedo tomar mi array y sumarlo consigo mismo, y se hará una suma elemento por elemento.
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [118]:
# Algo importante a tener en cuenta es que cuando intentas realizar cosas como dividir por 0 o por infinito, numpy no generará un error completo.
# En su lugar, solo dará una advertencia (warning).
# Por ejemplo, en nuestro array original tenemos un 0. Si intento hacer 1 dividido por el array, no se puede realmente hacer 1 dividido por 0.
# Pero si hago esto en numpy, igual veré un resultado:
# numpy pondrá una advertencia diciendo que encontró una división por 0 y, en lugar de dar un error, pondrá como marcador de posición el símbolo de infinito.
1/arr

/tmp/ipykernel_2069/3129781172.py:6: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
# Si digo array dividido por array, verás otra advertencia mostrando que se encontraron valores inválidos durante la división, y pondrá nan (“not a number”) cuando el resultado es 0 dividido por 0.
# Cualquier número dividido por 0 será infinito, y 0 dividido por 0 será nan.
# Fíjate que son advertencias, no errores completos, porque igual ves un resultado.
arr/arr

/tmp/ipykernel_2069/1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

## Funciones universales para arrays

In [120]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [121]:
np.log(arr)

/tmp/ipykernel_2069/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [122]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [124]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [125]:
9+8+7+6+5+4+3+2+1

45

In [123]:
arr.sum()

np.int64(45)

In [126]:
arr.mean()

np.float64(4.5)

In [127]:
arr.max()

np.int64(9)

In [130]:
# También se puede especificar un “axis” cuando trabajas con arrays de dos dimensiones.
# Por ejemplo, si quieres la suma de todas las columnas o de todas las filas, puedes indicarlo con el argumento axis.
arr_2d = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [131]:
arr_2d.shape

(3, 4)

In [ ]:
arr_2d.sum() #suma todos los números del array.

np.int64(78)

In [ ]:
# Pero si quieres sumar solo los valores de cada columna o de cada fila, puedes pasar el argumento axis: array2d.sum(axis=0) o array2d.sum(axis=1).
# Si pones axis=0, sumas a través de las filas para cada columna (es decir, suma vertical) y te devuelve la suma de cada columna.
# Piensa que axis=0 es “a lo largo de las filas” (o sea, vertical), así que regresa la suma por columna.
arr_2d.sum(axis=0)

array([15, 18, 21, 24])

In [ ]:
# Si pones axis=1, sumas a lo largo de las columnas para cada fila (es decir, suma horizontal), devolviendo la suma de cada fila.
arr_2d.sum(axis=1)

array([10, 26, 42])